name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Install Rust
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Publish to crates.io
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }} 